'use strict';
const $=id=>document.getElementById(id);
const config=window.HARUTOON_CONFIG;
const dateKey=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const validDate=k=>/^\d{4}-\d{2}-\d{2}$/.test(k)&&dateKey(new Date(k+'T12:00:00'))===k;
const validImage=s=>typeof s==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s);
let entries={},selected=dateKey(new Date()),cursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
let accessToken='',expires=0,expiryTimer,epoch=0,busy=false;
const images=new Map(),pending=new Map();
function toast(s){$('status').textContent=s;$('status').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('status').style.display='none',9000)}
function setBusy(v){busy=v;document.querySelectorAll('button,input').forEach(el=>el.disabled=v)}
function clearRecords(){epoch++;entries={};for(const u of images.values())URL.revokeObjectURL(u);images.clear();pending.clear();$('calendar').replaceChildren();$('detail').replaceChildren();$('large').removeAttribute('src');if($('viewer').open)$('viewer').close();$('diary').hidden=true;$('locked').hidden=false}
function lock(message='내 계정으로 로그인하면 그림일기가 펼쳐져요.'){accessToken='';expires=0;clearTimeout(expiryTimer);clearRecords();$('refresh').hidden=true;$('logout').hidden=true;$('connect').hidden=false;$('mode').textContent=message}
async function request(url,raw=false){if(!accessToken||Date.now()>=expires){lock('로그인이 만료됐어요. 다시 로그인해주세요.');throw new Error('다시 로그인해주세요.')}const r=await fetch(url,{headers:{Authorization:'Bearer '+accessToken},cache:'no-store'});if(!r.ok){if(r.status===401)lock('로그인이 만료됐어요. 다시 로그인해주세요.');throw new Error(r.status===403?'Google Drive 권한 또는 기관의 앱 승인 정책을 확인해주세요.':r.status===404?'하루툰 폴더 또는 파일을 찾지 못했어요.':'Google Drive 요청에 실패했어요. ('+r.status+')')}return raw?r:r.json()}
const drive=(path,params={})=>request('https://www.googleapis.com/drive/v3/'+path+'?'+new URLSearchParams(params));
async function list(parent){let token='',all=[];do{const r=await drive('files',{q:"'"+parent+"' in parents and trashed = false",fields:'nextPageToken,files(id,name,mimeType)',pageSize:'1000',...(token?{pageToken:token}:{})});all.push(...r.files);token=r.nextPageToken||''}while(token);return all}
async function content(id){return request('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?alt=media',true)}
function normalize(e,date){if(!e||typeof e.title!=='string'||e.title.length>100||typeof e.story!=='string'||e.story.length>50000||typeof e.mood!=='string'||e.mood.length>100)throw new Error(date+' 일기의 형식을 확인해주세요.');if(e.image&&!validImage(e.image))throw new Error(date+' 그림 형식을 확인해주세요.');if(e.imageId&&typeof e.imageId!=='string')throw new Error(date+' 그림 파일 ID를 확인해주세요.');return {title:e.title,story:e.story,mood:e.mood,image:e.image||'',imageId:e.imageId||'',imageFile:e.imageFile||''}}
async function loadCloud(){const g=epoch;await drive('files/'+config.folderId,{fields:'id,mimeType'});const root=await list(config.folderId),folders=root.filter(f=>f.mimeType==='application/vnd.google-apps.folder'&&['diaries','images'].includes(f.name));let files=[...root];for(const folder of folders)files.push(...await list(folder.id));const byName=new Map(files.map(f=>[f.name,f.id])),next={};const records=files.filter(f=>/^\d{4}-\d{2}-\d{2}\.json$/.test(f.name));for(let i=0;i<records.length;i+=4){await Promise.all(records.slice(i,i+4).map(async f=>{const k=f.name.slice(0,10);if(!validDate(k))throw new Error('일기 날짜를 확인해주세요: '+f.name);const e=await(await content(f.id)).json();if(e.format!=='harutoon-entry'||e.version!==1)throw new Error('하루툰 일기 형식이 아니에요: '+f.name);const entry=normalize(e,k);if(entry.imageFile&&!entry.imageId){if(typeof entry.imageFile!=='string'||!byName.has(entry.imageFile))throw new Error(k+' 그림 파일을 찾지 못했어요.');entry.imageId=byName.get(entry.imageFile)}if(next[k])throw new Error(k+' 일기가 중복되어 있어요. 파일을 확인해주세요.');next[k]=entry}))}if(g!==epoch)return;for(const u of images.values())URL.revokeObjectURL(u);images.clear();pending.clear();epoch++;entries=next;render()}
async function imageFor(e){if(e.image)return e.image;if(!e.imageId)return '';if(images.has(e.imageId))return images.get(e.imageId);if(pending.has(e.imageId))return pending.get(e.imageId);const g=epoch;const task=(async()=>{const blob=await(await content(e.imageId)).blob();if(!['image/png','image/jpeg','image/webp'].includes(blob.type))throw new Error('지원하지 않는 그림 파일 형식이에요.');const url=URL.createObjectURL(blob);if(g!==epoch){URL.revokeObjectURL(url);return ''}images.set(e.imageId,url);return url})();pending.set(e.imageId,task);try{return await task}finally{if(g===epoch)pending.delete(e.imageId)}}
function paint(im,e){const g=epoch;imageFor(e).then(u=>{if(g===epoch&&im.isConnected&&u){im.src=u;im.hidden=false}}).catch(err=>{if(g===epoch&&im.isConnected){im.hidden=true;im.title=err.message;if(im.classList.contains('detail-image')){const p=document.createElement('p');p.textContent='그림을 불러오지 못했어요. '+err.message;im.after(p)}}})}
function render(){if(!accessToken)return;$('locked').hidden=true;$('diary').hidden=false;$('connect').hidden=true;$('refresh').hidden=false;$('logout').hidden=false;$('mode').textContent='☁ Google Drive · 하루툰에 연결됨';const y=cursor.getFullYear(),m=cursor.getMonth();$('month').textContent=y+'년 '+(m+1)+'월';$('count').textContent=Object.keys(entries).filter(k=>k.startsWith(y+'-'+String(m+1).padStart(2,'0'))).length+'편의 이야기가 있어요';$('calendar').replaceChildren();for(const name of ['일','월','화','수','목','금','토']){const d=document.createElement('div');d.className='weekday';d.textContent=name;$('calendar').append(d)}for(let i=0;i<new Date(y,m,1).getDay();i++)$('calendar').append(document.createElement('div'));for(let n=1;n<=new Date(y,m+1,0).getDate();n++){const k=dateKey(new Date(y,m,n)),e=entries[k],b=document.createElement('button');b.className='day'+(k===selected?' selected':'')+(k===dateKey(new Date())?' today':'');b.textContent=n;b.setAttribute('aria-label',k+(e?' '+e.title:''));if(e?.image||e?.imageId){const im=document.createElement('img');im.alt='';im.hidden=true;b.append(im);paint(im,e)}else if(e){const d=document.createElement('div');d.textContent='✍️';b.append(d)}b.onclick=()=>{selected=k;render()};$('calendar').append(b)}detail()}
function detail(){const e=entries[selected];$('detail').replaceChildren();const h=document.createElement('h2');h.textContent=selected.replaceAll('-','. ');$('detail').append(h);if(!e){const p=document.createElement('p');p.className='empty';p.textContent='🌱 아직 기록이 없는 날이에요. 이 대화에 일기를 남겨주세요.';$('detail').append(p);return}const title=document.createElement('h2'),mood=document.createElement('p'),story=document.createElement('p');title.textContent=e.title;mood.textContent=e.mood;story.textContent=e.story;story.className='story';$('detail').append(title,mood);if(e.image||e.imageId){const im=document.createElement('img');im.className='detail-image';im.alt=e.title;im.hidden=true;paint(im,e);im.onclick=()=>{if(accessToken&&im.src){$('large').src=im.src;$('viewer').showModal()}};$('detail').append(im)}$('detail').append(story)}
async function authenticated(response){if(response.error){toast('로그인이 취소되었거나 승인되지 않았어요.');return}setBusy(true);clearRecords();accessToken=response.access_token;expires=Date.now()+Number(response.expires_in)*1000;const g=epoch;try{const user=await request('https://www.googleapis.com/oauth2/v3/userinfo');if(user.email!==config.allowedEmail||user.email_verified!==true)throw new Error('등록된 하루툰 계정으로 로그인해주세요.');if(g!==epoch)return;expiryTimer=setTimeout(()=>lock('로그인이 만료됐어요. 다시 로그인해주세요.'),Math.max(0,expires-Date.now()));await loadCloud()}catch(e){lock('연결을 완료하지 못했어요. Google 로그인을 다시 진행해주세요.');toast(e.message)}finally{setBusy(false)}}
function signIn(){const clientId=config.googleClientId||localStorage.getItem('harutoon-google-client')||'';if(!clientId){openConfig();return}if(!window.google?.accounts?.oauth2){toast('Google 로그인 기능이 아직 준비되지 않았어요. 잠시 후 다시 눌러주세요.');return}google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'openid email https://www.googleapis.com/auth/drive.readonly',include_granted_scopes:false,callback:authenticated,error_callback:()=>toast('Google 로그인 창이 닫혔거나 팝업이 차단됐어요.')}).requestAccessToken({prompt:'select_account'})}
function openConfig(){$('client').value=config.googleClientId||localStorage.getItem('harutoon-google-client')||'';$('config').showModal()}
$('connect').onclick=signIn;$('settings').onclick=openConfig;$('configClose').onclick=()=>$('config').close();$('configSave').onclick=()=>{const id=$('client').value.trim();if(!/^[\w.-]+\.apps\.googleusercontent\.com$/.test(id)){toast('Google OAuth 클라이언트 ID를 확인해주세요.');return}lock();localStorage.setItem('harutoon-google-client',id);$('config').close();toast('설정했어요. Google로 로그인을 눌러주세요.')};
$('logout').onclick=()=>{lock();toast('로그아웃했어요. 화면의 글과 그림을 지웠어요.')};
$('refresh').onclick=async()=>{setBusy(true);clearRecords();try{await loadCloud()}catch(e){lock('기록을 불러오지 못했어요. 다시 로그인해주세요.');toast(e.message)}finally{setBusy(false)}};
$('prev').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);render()};$('next').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);render()};$('today').onclick=()=>{selected=dateKey(new Date());cursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);render()};$('closeViewer').onclick=()=>$('viewer').close();
function blobData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('그림을 읽지 못했어요.'));r.readAsDataURL(blob)})}
$('backup').onclick=async()=>{if(busy||!accessToken)return;setBusy(true);const g=epoch;try{const result={};for(const [k,e] of Object.entries(entries)){let image=await imageFor(e);if(image.startsWith('blob:'))image=await blobData(await(await fetch(image)).blob());if(g!==epoch||!accessToken)throw new Error('로그인이 만료됐어요. 다시 로그인 후 백업해주세요.');result[k]={title:e.title,story:e.story,mood:e.mood,image}}const url=URL.createObjectURL(new Blob([JSON.stringify({format:'harutoon',version:1,entries:result},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='하루툰_백업_'+dateKey(new Date())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){toast(e.message)}finally{setBusy(false)}};
window.addEventListener('pagehide',()=>lock());
lock();
