'use strict';
const $=id=>document.getElementById(id), graphRoot='https://graph.microsoft.com/v1.0', scopes='https://graph.microsoft.com/Files.ReadWrite';
const dateKey=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const validDate=k=>/^\d{4}-\d{2}-\d{2}$/.test(k)&&dateKey(new Date(k+'T12:00:00'))===k;
const validImage=s=>typeof s==='string'&&(!s||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s));
const validateEntry=e=>e&&typeof e.title==='string'&&e.title.length<=100&&typeof e.story==='string'&&e.story.length<=50000&&typeof e.mood==='string'&&e.mood.length<=100;
const uuid=()=>crypto.randomUUID(), redirectUri=location.origin+location.pathname;
let entries={},selected=dateKey(new Date()),cursor=new Date(new Date().getFullYear(),new Date().getMonth(),1),editing=false,busy=false,draftImage='',originalImage='',cloud=false,folderId='',diaryFolder='',imageFolder='',images=new Map(),pendingImages=new Map(),generation=0;
let appConfig={...window.HARUTOON_CONFIG,...JSON.parse(localStorage.getItem('harutoon-config')||'{}')};
let auth=JSON.parse(sessionStorage.getItem('harutoon-auth')||'null');
function toast(s){$('status').textContent=s;$('status').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('status').style.display='none',6500)}
function showError(e){toast(e.status===412||e.status===409?'다른 기기에서 이 일기가 바뀌었어요. 작성 내용을 복사해 두고 취소 → 새로고침 후 다시 저장해주세요.':e.message||'처리하지 못했어요.')}
function setBusy(v){busy=v;document.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=v)}
function leave(){return !busy&&(!editing||confirm('작성 중인 내용은 저장되지 않았어요. 이동할까요?'))}
function resetImages(){generation++;for(const u of images.values())if(u.startsWith('blob:'))URL.revokeObjectURL(u);images.clear();pendingImages.clear()}
function download(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('harutoon-v2',1);req.onupgradeneeded=()=>req.result.createObjectStore('entries');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(new Error('브라우저 저장소를 열지 못했어요. 브라우저 설정을 확인해주세요.'))});
async function localRead(){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('entries'),store=tx.objectStore('entries'),keys=store.getAllKeys(),vals=store.getAll();tx.oncomplete=()=>resolve(Object.fromEntries(keys.result.map((k,i)=>[k,vals.result[i]])));tx.onerror=()=>reject(tx.error)})}
async function localWrite(k,e){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('entries','readwrite');e?tx.objectStore('entries').put(e,k):tx.objectStore('entries').delete(k);tx.oncomplete=resolve;tx.onerror=()=>reject(new Error('브라우저 저장 공간이 부족하거나 저장이 차단됐어요. 백업해주세요.'))})}
function base64url(arr){return btoa(String.fromCharCode(...arr)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function signIn(){if(!leave())return;if(!appConfig.clientId||!appConfig.tenantId){openConfig();return}if(!/^https?:$/.test(location.protocol))throw new Error('OneDrive 연결은 홈페이지 주소에서 이용해주세요.');const verifier=base64url(crypto.getRandomValues(new Uint8Array(48))),state=uuid(),challenge=base64url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));sessionStorage.setItem('harutoon-oauth',JSON.stringify({verifier,state,created:Date.now()}));const q=new URLSearchParams({client_id:appConfig.clientId,response_type:'code',redirect_uri:redirectUri,response_mode:'query',scope:scopes+' offline_access',state,code_challenge:challenge,code_challenge_method:'S256',prompt:'select_account'});location.assign('https://login.microsoftonline.com/'+appConfig.tenantId+'/oauth2/v2.0/authorize?'+q)}
async function tokenRequest(params){const r=await fetch('https://login.microsoftonline.com/'+appConfig.tenantId+'/oauth2/v2.0/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:appConfig.clientId,scope:scopes+' offline_access',...params})});const v=await r.json();if(!r.ok)throw new Error('Microsoft 로그인을 완료하지 못했어요. SPA 주소·권한 또는 학교의 승인 정책을 확인해주세요. ('+(v.error||r.status)+')');auth={access_token:v.access_token,refresh_token:v.refresh_token||auth?.refresh_token,expires:Date.now()+v.expires_in*1000};sessionStorage.setItem('harutoon-auth',JSON.stringify(auth));return auth.access_token}
async function callback(){const q=new URLSearchParams(location.search);if(!q.has('code')&&!q.has('error'))return;const saved=JSON.parse(sessionStorage.getItem('harutoon-oauth')||'null');history.replaceState(null,'',location.pathname);sessionStorage.removeItem('harutoon-oauth');if(!saved||saved.state!==q.get('state')||Date.now()-saved.created>15*60*1000)throw new Error('로그인 확인 정보가 만료됐어요. 다시 연결해주세요.');if(q.has('error'))throw new Error('학교 계정 로그인이 취소되었거나 승인되지 않았어요. ('+q.get('error')+')');await tokenRequest({grant_type:'authorization_code',code:q.get('code'),redirect_uri:redirectUri,code_verifier:saved.verifier})}
let renewing;async function token(){if(!auth)throw new Error('학교 OneDrive에 다시 로그인해주세요.');if(auth.expires>Date.now()+60000)return auth.access_token;if(!auth.refresh_token)throw new Error('로그인이 만료됐어요. 다시 연결해주세요.');if(!renewing)renewing=tokenRequest({grant_type:'refresh_token',refresh_token:auth.refresh_token}).finally(()=>renewing=null);return renewing}
async function graph(path,opts={}){const url=path.startsWith('https:')?path:graphRoot+path;if(!url.startsWith(graphRoot+'/'))throw new Error('올바르지 않은 요청 주소입니다.');const r=await fetch(url,{...opts,headers:{Authorization:'Bearer '+await token(),...opts.headers}});if(!r.ok){const e=new Error(r.status===401?'로그인이 만료됐어요. 다시 연결해주세요.':r.status===403?'학교 정책 또는 OneDrive 접근 권한을 확인해주세요.':'OneDrive 요청을 완료하지 못했어요. ('+r.status+')');e.status=r.status;throw e}return r.status===204?null:r.json()}
async function getContent(id){const meta=await graph('/me/drive/items/'+encodeURIComponent(id)+'?$select=id,@microsoft.graph.downloadUrl'),url=meta['@microsoft.graph.downloadUrl'];if(!url||!url.startsWith('https://'))throw new Error('파일 다운로드 주소를 받지 못했어요.');const r=await fetch(url);if(!r.ok)throw new Error('OneDrive 파일을 읽지 못했어요.');return r}
async function folder(parent,name){try{return await graph('/me/drive/'+parent+':/'+encodeURIComponent(name)+'?'+new URLSearchParams({'$select':'id,name,folder'}))}catch(e){if(e.status!==404)throw e;try{return await graph('/me/drive/'+parent+'/children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':'fail'})})}catch(e2){if(e2.status===409)return graph('/me/drive/'+parent+':/'+encodeURIComponent(name));throw e2}}}
async function connectDrive(){await graph('/me/drive?$select=id');const root=await folder('root','Harutoon');if(!root.folder)throw new Error('OneDrive의 Harutoon이 폴더가 아니에요. 이름을 확인해주세요.');folderId=root.id;const diary=await folder('items/'+folderId,'diaries'),photo=await folder('items/'+folderId,'images');diaryFolder=diary.id;imageFolder=photo.id;await loadCloud();cloud=true}
async function children(id){let path='/me/drive/items/'+id+'/children?$select=id,name,eTag&$top=200',all=[];while(path){let r=await graph(path);all.push(...r.value);path=r['@odata.nextLink']}return all}
async function loadCloud(){const files=(await children(diaryFolder)).filter(f=>/^\d{4}-\d{2}-\d{2}\.json$/.test(f.name)),next={};for(let i=0;i<files.length;i+=4){await Promise.all(files.slice(i,i+4).map(async f=>{const e=await(await getContent(f.id)).json(),k=f.name.slice(0,10);if(!validDate(k)||!validateEntry(e)||e.format!=='harutoon-entry'||e.version!==1||(e.imageId&&typeof e.imageId!=='string'))throw new Error('OneDrive에 형식이 다른 일기가 있어요: '+f.name);next[k]={...e,_id:f.id,_etag:f.eTag}}))}resetImages();entries=next}
async function imageFor(e){if(e.image)return e.image;if(!e.imageId)return '';if(images.has(e.imageId))return images.get(e.imageId);if(pendingImages.has(e.imageId))return pendingImages.get(e.imageId);const g=generation,task=(async()=>{const r=await getContent(e.imageId),u=URL.createObjectURL(await r.blob());if(g!==generation){URL.revokeObjectURL(u);return ''}images.set(e.imageId,u);return u})();pendingImages.set(e.imageId,task);try{return await task}finally{if(g===generation)pendingImages.delete(e.imageId)}}
function paintImage(im,e){const g=generation;imageFor(e).then(u=>{if(g===generation&&im.isConnected){im.src=u;im.hidden=!u}}).catch(()=>{im.hidden=true})}
async function cloudSave(k,e,previous){let imageId=previous?.imageId||'';if(e.image!==undefined&&e.image!==originalImage){if(e.image){const blob=await(await fetch(e.image)).blob();const im=await graph('/me/drive/items/'+imageFolder+':/'+k+'-'+uuid()+'.jpg:/content',{method:'PUT',headers:{'Content-Type':'image/jpeg'},body:blob});imageId=im.id}else imageId=''}else if(e.image&&!imageId){const blob=await(await fetch(e.image)).blob();const im=await graph('/me/drive/items/'+imageFolder+':/'+k+'-'+uuid()+'.jpg:/content',{method:'PUT',headers:{'Content-Type':'image/jpeg'},body:blob});imageId=im.id}
const record={format:'harutoon-entry',version:1,title:e.title,story:e.story,mood:e.mood,imageId,updatedAt:new Date().toISOString()};const headers={'Content-Type':'application/json'};if(previous?._etag)headers['If-Match']=previous._etag;const path=previous?._id?'/me/drive/items/'+previous._id+'/createUploadSession':'/me/drive/items/'+diaryFolder+':/'+k+'.json:/createUploadSession';const session=await graph(path,{method:'POST',headers,body:JSON.stringify({item:{'@microsoft.graph.conflictBehavior':previous?._id?'replace':'fail'}})});if(!session.uploadUrl?.startsWith('https://'))throw new Error('저장 주소를 받지 못했어요.');const blob=new Blob([JSON.stringify(record)],{type:'application/json'}),r=await fetch(session.uploadUrl,{method:'PUT',headers:{'Content-Type':'application/json','Content-Range':'bytes 0-'+(blob.size-1)+'/'+blob.size},body:blob});if(!r.ok){const err=new Error('OneDrive 저장을 완료하지 못했어요. ('+r.status+')');err.status=r.status;throw err}const item=await r.json();if(!item.id||!item.eTag)throw new Error('저장 결과를 확인하지 못했어요. 새로고침 후 확인해주세요.');return {...record,_id:item.id,_etag:item.eTag}}
async function save(k,e){const old=entries[k];if(cloud){entries[k]=await cloudSave(k,e,old)}else{await localWrite(k,e);entries[k]=e}}
function mode(){$('mode').textContent=cloud?'☁ 학교 OneDrive에 연결됨 · 저장 후 다른 기기에서 새로고침하면 반영돼요.':'💻 이 브라우저에 저장 중 · 기기 간 공유하려면 학교 OneDrive를 연결해주세요.';$('connect').textContent=cloud?'계정 다시 연결':'☁ 학교 OneDrive 연결';$('refresh').hidden=!cloud;$('logout').hidden=!auth}
function render(){mode();const y=cursor.getFullYear(),m=cursor.getMonth();$('month').textContent=y+'년 '+(m+1)+'월';$('count').textContent=Object.keys(entries).filter(k=>k.startsWith(y+'-'+String(m+1).padStart(2,'0'))).length+'편의 이야기가 있어요';$('calendar').replaceChildren();['일','월','화','수','목','금','토'].forEach(t=>{const d=document.createElement('div');d.className='weekday';d.textContent=t;$('calendar').append(d)});for(let i=0;i<new Date(y,m,1).getDay();i++)$('calendar').append(document.createElement('div'));for(let n=1;n<=new Date(y,m+1,0).getDate();n++){const k=dateKey(new Date(y,m,n)),e=entries[k],b=document.createElement('button');b.className='day'+(k===selected?' selected':'')+(k===dateKey(new Date())?' today':'');b.textContent=n;b.setAttribute('aria-label',k+(e?' 일기 있음':''));if(e?.image||e?.imageId){const im=document.createElement('img');im.alt='';im.hidden=true;b.append(im);paintImage(im,e)}else if(e){const d=document.createElement('div');d.textContent='✍️';b.append(d)}b.onclick=()=>{if(leave()){selected=k;editing=false;render()}};$('calendar').append(b)}detail()}
function button(label,fn,cls=''){const b=document.createElement('button');b.textContent=label;b.onclick=fn;b.className=cls;return b}
function detail(){const e=entries[selected];$('detail').replaceChildren();const h=document.createElement('h2');h.textContent=selected.replaceAll('-','. ');$('detail').append(h);if(!e){const d=document.createElement('div');d.className='empty';d.innerHTML='<h3>🌱 어떤 하루였나요?</h3><p class="muted">소소한 순간도 남겨보세요.</p>';$('detail').append(d)}else{const title=document.createElement('h2');title.textContent=e.title;const mood=document.createElement('p');mood.textContent=e.mood;$('detail').append(title,mood);if(e.image||e.imageId){const im=document.createElement('img');im.className='detail-image';im.alt=e.title;im.hidden=true;paintImage(im,e);im.onclick=()=>{if(im.src){$('large').src=im.src;$('viewer').showModal()}};$('detail').append(im)}const p=document.createElement('p');p.className='story';p.textContent=e.story;$('detail').append(p)}const actions=document.createElement('div');actions.className='actions';actions.append(button(e?'일기 수정':'이날의 일기 쓰기',()=>form().catch(showError),'primary'));if(e)actions.append(button('삭제',async()=>{if(busy||!confirm('이 날짜의 일기를 삭제할까요?'))return;setBusy(true);try{if(cloud)await graph('/me/drive/items/'+e._id,{method:'DELETE',headers:{'If-Match':e._etag}});else await localWrite(selected,null);delete entries[selected];render();toast('일기를 삭제했어요.')}catch(err){showError(err)}finally{setBusy(false)}}));$('detail').append(actions)}
async function form(){if(busy)return;setBusy(true);try{const e=entries[selected]||{};const image=await imageFor(e);if(image.startsWith('blob:')){originalImage=await blobData(await(await fetch(image)).blob())}else originalImage=image;draftImage=originalImage;editing=true;$('detail').innerHTML='<h2>'+selected+' · 일기 쓰기</h2><label for="title">오늘의 제목</label><input id="title" maxlength="100" placeholder="오늘 하루를 한 문장으로"><label for="mood">그날의 기분</label><select id="mood"><option>😊 행복해</option><option>💡 뿌듯해</option><option>😌 평온해</option><option>😂 웃겼어</option><option>😵 피곤해</option><option>🥲 속상해</option><option>😶 즐겁지만 찝찝해</option></select><label for="story">오늘 있었던 일</label><textarea id="story" maxlength="50000" placeholder="무슨 일이 있었고, 어떤 마음이 들었나요?"></textarea><label for="image">그림일기 첨부</label><input id="image" type="file" accept="image/*"><small>그림은 긴 변 1600px로 줄여 저장해요.</small><img id="preview" class="detail-image" style="margin-top:12px"><div class="actions"><button id="removeImage">그림 빼기</button><button id="save" class="primary">저장하기</button><button id="cancel">취소</button></div>';$('title').value=e.title||'';$('story').value=e.story||'';if(e.mood&&!Array.from($('mood').options).some(o=>o.value===e.mood))$('mood').add(new Option(e.mood,e.mood));$('mood').value=e.mood||'😊 행복해';preview();$('removeImage').onclick=()=>{draftImage='';$('image').value='';preview()};$('cancel').onclick=()=>{if(leave()){editing=false;render()}};$('image').onchange=async ev=>{const f=ev.target.files[0];if(!f)return;setBusy(true);try{if(f.size>30*1024*1024)throw new Error('30MB 이하의 그림을 선택해주세요.');draftImage=await resize(f);preview()}catch(err){showError(err)}finally{setBusy(false)}};$('save').onclick=async()=>{const e={title:$('title').value.trim(),story:$('story').value.trim(),mood:$('mood').value,image:draftImage};if(!e.title||(!e.story&&!e.image)){toast('제목과 이야기 또는 그림을 입력해주세요.');return}setBusy(true);try{await save(selected,e);editing=false;render();toast('오늘의 이야기를 저장했어요 🌷')}catch(err){showError(err)}finally{setBusy(false)}}}finally{setBusy(false)}}
function preview(){$('preview').src=draftImage;$('preview').hidden=!draftImage}
function blobData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('그림을 읽지 못했어요.'));r.readAsDataURL(blob)})}
function resize(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{try{const k=Math.min(1,1600/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.85))}catch(e){reject(e)}finally{URL.revokeObjectURL(u)}};im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('이미지를 읽지 못했어요. JPG 또는 PNG를 선택해주세요.'))};im.src=u})}
function openConfig(){if(!leave())return;$('client').value=appConfig.clientId||'';$('tenant').value=appConfig.tenantId||'';$('redirect').textContent=redirectUri;$('config').showModal()}
$('settings').onclick=openConfig;$('configClose').onclick=()=>$('config').close();$('configSave').onclick=()=>{const clientId=$('client').value.trim(),tenantId=$('tenant').value.trim(),re=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;if(!re.test(clientId)||!re.test(tenantId)){toast('두 ID를 정확히 입력해주세요.');return}if(auth&&(clientId!==appConfig.clientId||tenantId!==appConfig.tenantId)){toast('로그아웃 후 설정을 바꿔주세요.');return}appConfig={clientId,tenantId};localStorage.setItem('harutoon-config',JSON.stringify(appConfig));$('config').close();toast('설정을 저장했어요. 학교 OneDrive 연결을 눌러주세요.')};$('connect').onclick=()=>signIn().catch(showError);
$('prev').onclick=()=>{if(leave()){editing=false;cursor.setMonth(cursor.getMonth()-1);render()}};$('next').onclick=()=>{if(leave()){editing=false;cursor.setMonth(cursor.getMonth()+1);render()}};$('today').onclick=()=>{if(leave()){editing=false;selected=dateKey(new Date());cursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);render()}};$('closeViewer').onclick=()=>$('viewer').close();
$('refresh').onclick=async()=>{if(!leave())return;setBusy(true);try{await loadCloud();editing=false;render();toast('OneDrive에서 최신 기록을 불러왔어요.')}catch(e){showError(e)}finally{setBusy(false)}};
$('logout').onclick=async()=>{if(!leave())return;setBusy(true);auth=null;sessionStorage.removeItem('harutoon-auth');cloud=false;folderId=diaryFolder=imageFolder='';resetImages();$('large').removeAttribute('src');try{entries=await localRead();editing=false;render();toast('앱 연결을 해제했어요. 이 브라우저의 일기를 표시합니다.')}catch(e){showError(e)}finally{setBusy(false)}};
$('backup').onclick=async()=>{if(busy)return;setBusy(true);try{const backup={};for(const [k,e] of Object.entries(entries)){let image=await imageFor(e);if(image.startsWith('blob:'))image=await blobData(await(await fetch(image)).blob());backup[k]={title:e.title,story:e.story,mood:e.mood,image}}download('하루툰_백업_'+dateKey(new Date())+'.json',{format:'harutoon',version:1,entries:backup});toast('저장된 기록을 백업했어요. 작성 중인 내용은 포함되지 않아요.')}catch(e){showError(e)}finally{setBusy(false)}};
$('restore').onclick=()=>{if(leave())$('restoreFile').click()};$('restoreFile').onchange=async ev=>{const f=ev.target.files[0];if(!f)return;let done=0;try{if(f.size>100*1024*1024)throw new Error('100MB 이하의 백업을 선택해주세요.');const data=JSON.parse(await f.text());if(data.format!=='harutoon'||data.version!==1||!data.entries||Array.isArray(data.entries)||typeof data.entries!=='object')throw new Error('올바른 하루툰 백업을 선택해주세요.');for(const [k,e] of Object.entries(data.entries))if(!validDate(k)||!validateEntry(e)||!validImage(e.image))throw new Error('백업에 올바르지 않은 일기가 있어요.');const total=Object.keys(data.entries).length;if(!total)throw new Error('백업에 일기가 없어요.');if(!confirm(total+'편을 '+(cloud?'학교 OneDrive':'이 브라우저')+'에 가져올까요? 이미 있는 날짜는 건너뜁니다.'))return;setBusy(true);for(const [k,e] of Object.entries(data.entries)){if(entries[k])continue;const im=e.image?await resize(await(await fetch(e.image)).blob()):'';originalImage='';await save(k,{title:e.title,story:e.story,mood:e.mood,image:im});done++;$('mode').textContent='가져오는 중… '+done+'/'+total}editing=false;render();toast(done+'편을 가져왔어요. 기존 날짜는 유지했어요.')}catch(e){showError(new Error((done?done+'편까지 저장됐어요. 다시 가져오면 이어서 진행합니다. ':'')+e.message));if(!editing)render()}finally{setBusy(false);ev.target.value=''}};
window.addEventListener('beforeunload',e=>{if(editing||busy){e.preventDefault();e.returnValue=''}});
async function init(){setBusy(true);try{await callback();if(auth)await connectDrive();else entries=await localRead();render()}catch(e){showError(e);if(!cloud){entries=await localRead().catch(()=>({}));render()}else{$('mode').textContent='OneDrive 기록을 불러오지 못했어요. 다시 연결해주세요.';$('logout').hidden=false;$('detail').textContent='연결이 복구되기 전에는 기록을 작성할 수 없어요.';return}}finally{setBusy(false)}}
init();
